### ISSUE TITLE
Default the profile to `AWS_PROFILE` environment variable

### ISSUE THREAD

**Issue by ChrisRut** [gjbae1212/gossm#1]
First off, this is a great tool, thank you for open sourcing it...

The issue I am currently running into is that I have to specify the `-p` profile for every call I make, because I have multiple accounts I also have multiple profiles, the way I deal with this when using `boto3` or the `aws-sdk-go` directly is I set the `AWS_PROFILE` environment variable:

> By default, the SDK checks the AWS_PROFILE environment variable to determine which profile to use. If no AWS_PROFILE variable is set, the SDK uses the default profile.

- https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-profiles

It seems `gossm` is not respecting this environment variable and is instead always defaulting to the `default` profile.  It would be great if this instead first checked to see if the `AWS_PROFILE` was set and used that instead, like all the AWS SDKs work today.

Thanks again,
-Chris

**Comment by gjbae1212** [comment]
It’s good idea. I will update it as soon as possible.

**Comment by gjbae1212** [comment]
[Release] https://github.com/gjbae1212/gossm/releases/tag/v1.0.3.
