### ISSUE TITLE
Bug: Can't start an encrypted session

### ISSUE THREAD

**Issue by jonasneves** [gjbae1212/gossm#11]
I get the following error when I try to start a session on version `>=v1.1.0`

```
----------ERROR-------
Encountered error while initiating handshake. KMSEncryption failed on client with status 2 error: Failed to process action KMSEncryption: Error calling KMS GenerateDataKey API: UnrecognizedClientException: The security token included in the request is invalid.
	status code: 400, request id: b3ebe283-c1bf-4722-b553-8f08693a9694
```

gossm v1.0.5 works without any problem.

**Comment by jonasoneves** [comment]
Sorry, this issue can be closed. It was fixed on version 1.1.1!

**Comment by gjbae1212** [comment]
@jonasneves 
It's working well for me. 
I also have made sessions using KMS in AWS.
I would say, maybe AWS  [session-manager-plugin](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html) differents.
**gossm** have used session-manager-plugin internally, so this plugin is placed in $home/.gossm directory.

Check it session-manager-plugin. you can check to try it, such as **./session-manager-plugin --version**

At least, I do works session-manager-plugin 1.1.61.0.

**Comment by zswanson** [comment]
It appears that doing an upgrade of gossm doesn't update the session-manager plugin that's 'installed' in the home directory, if it has a minimum version required for gossm

**Comment by jonasneves** [comment]
Closing this as I'm not seeing the error anymore in the new version. Unfortunately, it's a different one though
