### ISSUE TITLE
No MFA support?

### ISSUE THREAD

**Issue by wimsymons** [gjbae1212/gossm#19]
Hi,

Today I downloaded gossm to see if it works for us.

But when I run:
```
gossm -p ****REDACTED**** start
```

It immediately fails with this error:
```
AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.
```

The profile I use, looks like:
```
[profile ****REDACTED****]
region = eu-west-1
source_profile = ****REDACTED****
role_arn = arn:aws:iam::****REDACTED****:role/****REDACTED****
mfa_serial = arn:aws:iam::****REDACTED****:mfa/****REDACTED****
cli_pager =
```

How can I make this work?

Kind regards

Wim

**Comment by tedsmitt** [comment]
Hey Wim, I've opened a [new PR](https://github.com/gjbae1212/gossm/pull/20) to add support for this.

**Comment by wimsymons** [comment]
Oooo Nice 👍 Thank you.

**Comment by tedsmitt** [comment]
@wimsymons Have you tried this using the latest version (1.2.3)? Let us know if it's fixed for you!

**Comment by wimsymons** [comment]
Yes I did, and it works perfectly. Thank you!
