### ISSUE TITLE
Add functionality to get current version from binary

### ISSUE THREAD

**Issue by moritzheiber** [gjbae1212/gossm#2]
For packaging reasons it would be ideal to be able to tell which version of the binary is currently installed. This is usually achieved by adding a `--version` switch. I'd love for `gossm` to have such a switch.

**Comment by gjbae1212** [comment]
Hello friend. 

Sorry, I just checked the issue.

But, I add a version flag in gossm(v1.1.0).

Thank you for your consideration.
