### ISSUE TITLE
Possible regression from v1.2.0 onwards when using aws-vault

### ISSUE THREAD

**Issue by Deichindianer** [gjbae1212/gossm#22]
I think I just found a regression from version 1.2.0 onwards when using environment variables for the authentication.

Output with version v1.2.0

```
[aws:devops-test] [pb:~/Downloads]$ gossm start 
[update] aws ssm plugin
[profile] default
NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

Output with version v1.1.1

```
[aws:devops-test] [pb:~/Downloads]$ gossm start
[update] aws ssm plugin
? Choose a target in AWS:  [Use arrows to move, type to filter]
> xxxxx	(i-xxxxxxxxxxxxxxxxxx)
  xxxxx	(i-xxxxxxxxxxxxxxxxxx)
```

Did something major change with the new version?

I've got a fairly basic AWS configuration with aws-vault profile injections

```
[profile prod]
include_profile=default
source_profile=default
role_arn=arn:aws:iam::0123456789012:role/role-name

[profile test]
include_profile=default
source_profile=default
role_arn=arn:aws:iam::0123456789012:role/role-name

[default]
region=eu-central-1
mfa_serial=arn:aws:iam::0123456789012:mfa/mail@example.com
```

**Comment by tedsmitt** [comment]
Hey @Deichindianer, can you try this with version 1.2.3? There was a [PR](https://github.com/gjbae1212/gossm/pull/21) to fix the tool using environment variables.

**Comment by Deichindianer** [comment]
Ah sorry, missed that somehow. v1.2.3 fixes the issue :) Thanks for the shout!
