### ISSUE TITLE
Can't start a new session, NoCredentialProviders: no valid providers in chain. Deprecated.

### ISSUE THREAD

**Issue by yaleman** [gjbae1212/gossm#28]
```shell
$ gossm start -p aws-292
[err] NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
$ gossm --version
gossm version 1.3.1
$ ~/.gossm/session-manager-plugin --version
1.2.30.0
```
This only happens when I'm using AWS in SSO mode, it works if I copy temporary credentials from the web interface.

**Comment by rtoma** [comment]
Similar.

When I have environment variables AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN set, I get the error.

When I copy the values to a profile (~/.aws/config and ~/.aws/credentials) and use it, gossm works.
