### ISSUE TITLE
Connection times out

### ISSUE THREAD

**Issue by eskp** [gjbae1212/gossm#3]
Started getting this error:

```----------ERROR-------
Encountered error while initiating handshake. KMSEncryption failed on client with status 2 error: Failed to process action KMSEncryption: Error calling KMS GenerateDataKey API: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

However, starting a session through aws cli connects successsfully.

**Comment by gjbae1212** [comment]
Hello @eskp 

I check this issue soon.

Maybe, I need your help such as detailed logs, execute command ... and so on. 

Please comment it.

**Comment by eskp** [comment]
I think this has to do with IAM permissions when using KMS key for encryption. Closing.
