### ISSUE TITLE
Feature Request: Add Command for Port-Forwarding

### ISSUE THREAD

**Issue by tedsmitt** [gjbae1212/gossm#32]
On top of the already useful command set of this tool, I think it can be improved even further by adding a Port-Forwarding command. 

Making use of the `AWS-StartPortForwardingSession` SSM Document we can start a Port-Forwarding session entirely over SSM (See [here](https://aws.amazon.com/blogs/aws/new-port-forwarding-using-aws-system-manager-sessions-manager/) for an overview).

I have spiked this locally where I've added the `fwd` command. It prompts the user for the remote port to access and the local port to forward after selecting a target.

![image](https://user-images.githubusercontent.com/25430401/109038064-43047d00-76c3-11eb-8e8d-013aa7cddb13.png)
![image](https://user-images.githubusercontent.com/25430401/109037668-e30dd680-76c2-11eb-8d27-e3429a811afd.png)

Ports can be specified before selecting a target too, using the -z and -l args.

![image](https://user-images.githubusercontent.com/25430401/109038187-616a7880-76c3-11eb-9f4d-8c05178e4b4f.png)

I already have this written up and ready for a PR. Are there any objections to adding this to the existing command set?

**Comment by tedsmitt** [comment]
Created PR https://github.com/gjbae1212/gossm/pull/33

**Comment by gjbae1212** [comment]
@tedsmitt 
Apply it. gossm v1.3.2.
