### ISSUE TITLE
Extend support to ECS exec

### ISSUE THREAD

**Issue by dirk39** [gjbae1212/gossm#37]
Hi, recently AWS released the support to [ECS exec](https://aws.amazon.com/blogs/containers/new-using-amazon-ecs-exec-access-your-containers-fargate-ec2/), a way to open an interactive shell into a running container into ECS + EC2 and Fargate. What do you think to implement this functionality? I'm open to writing the necessary code.

Thanks

**Comment by tedsmitt** [comment]
Hey @dirk39 - I can't speak for the creator but when ECS exec was announced I thought about adding this to gossm. Ultimately I decided against this. Gossm is great at interacting with EC2 instances in a variety of ways, and I think having it do a lot of EC2 stuff, with a tiny bit of ECS on the bolted-on didn't feel right. 

With that said, I took the inspiration from gossm and made [ecsgo](https://github.com/tedsmitt/ecsgo). It does pretty much the same job as gossm except it allows for navigation between the different levels of abstraction in ECS. I'd welcome any issues/feedback on the project.
