### ISSUE TITLE
authenticate with aws credential_process

### ISSUE THREAD

**Issue by zaro0508** [gjbae1212/gossm#40]
We use the AWS SSM and when we run start-session we authenticate by [sourcing credentials with an external process](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html) which does not seem to work with gossm.  We have tested with other, more normal, profiles containing key and secret key definitions and those work just fine.  We are wondering whether we are missing something or whether  gossm just doesn't supports the `credential_process` way of authenticating at all?

Our `~/.aws/config` file is configured something like this:
```
[profile my-profile]
region=us-east-1 
credential_process = "/Users/zaro0508/creds.sh" "https://acme.org" "eyJ0eXAiO...2GLQg"
```

`creds.sh` makes a request to our service and returns a json like so:
```
➜ ~/creds.sh "https://acme.org" "eyJ0eXAiO...2GLQg"
{"SessionToken":"FwoGZXI...lOW6uY=","Version":1,"AccessKeyId":"XXXXXX1234","SecretAccessKey":"XXXXXXXXXX6789","Expiration":"2021-07-21T22:02:17Z"}
``` 

This setup works with the AWS CLI `aws ssm start-session` just fine.  However when we run with gossm it does not work.
```
➜  gossm start --profile my-profile
[err] ProcessProviderParseError: parse failed of credential_process output:

caused by: unexpected end of JSON input
```

**Comment by gjbae1212** [comment]
Maybe fix it in gossm v1.4.0.
