### ISSUE TITLE
Document Permissions Required for gossm

### ISSUE THREAD

**Issue by yhakbar** [gjbae1212/gossm#44]
Hello!

First of all, thanks for gossm. This tool is awesome!

We've recently run into permissions issues after upgrading to gossm 1.4.0, due to the added API call to `ssm:DescribeInstanceInformation`. Would it be possible to document the permissions required to utilize gossm so that developers can be assigned minimal privileges to work with it?

Also, in our testing, it seems like the following permissions need to be granted on all resources without restriction in order to use `gossm`:

```json
      "ssm:GetConnectionStatus",
      "ec2:DescribeInstances",
      "ssm:DescribeSessions",
      "ssm:DescribeInstanceProperties",
      "ssm:DescribeInstanceInformation"
```

Is there any way to reduce the permissions required to use this tool?

**Comment by gjbae1212** [comment]
Thank you. Write it to README.md.
