### ISSUE TITLE
FilterLimitExceeded: The maximum number of filter values specified on a single call is 200

### ISSUE THREAD

**Issue by bertofett** [gjbae1212/gossm#47]
[err] operation error EC2: DescribeInstances, https response error StatusCode: 400, RequestID: baec71f7-0ec1-4db4-bf27-59cfa6fc3127, api error FilterLimitExceeded: The maximum number of filter values specified on a single call is 200

This was resolved in[ #31]( https://github.com/gjbae1212/gossm/issues/31) , However it looks like it was reintroduced with newer releases. End user currently has 1.4.3 installed in an OSX Environment.

**Comment by gjbae1212** [comment]
@bertofett thank you. 
fixed it in gossm v1.4.4.
