### ISSUE TITLE
Feature request: list and connect to on prem instances

### ISSUE THREAD

**Issue by braun1928** [gjbae1212/gossm#5]
Currently the app only lists the EC2 instances, but lacks the possibility to list and connect managed instances that exist only in SSM, not in EC2. It would be great if those instances could be listed in the `gossm start` subcommand.

**Comment by tedsmitt** [comment]
Hey @braun1928 - I'm going to look into this for you, this is pretty key functionality imo.

**Comment by tedsmitt** [comment]
@braun1928 This should now work in v1.3.1

**Comment by braun1928** [comment]
@tedsmitt awesome! and much better than the changes I was trying locally. Thanks!
