### ISSUE TITLE
인라인으로 접속 할때 에러가 발생합니다.

### ISSUE THREAD

**Issue by MintChocoO2C** [gjbae1212/gossm#7]
인라인으로 접속 할때 에러를 발생합니다.
```
./gossm -r ap-northeast-1 -t i-XXXXXXXXXXX
[err] don't exist running instances
```

디버깅을 해 보니 PublicDNS가 없는 서버에 접속할때만 발생하는걸 확인하였습니다.

**Comment by gjbae1212** [comment]
Hello friend.

Maybe it has encountered using ec2 in private subnet. 

As far as I know,  AWS SSM internally has used WebSocket between client and server and must run in public subnet.

But if you want to use it in private subnet, neet to VPC endpoint.

Good example below.
https://docs.aws.amazon.com/systems-manager/latest/userguide/setup-create-vpc.html
https://ystatit.medium.com/aws-session-manager-walk-through-5c3ad28e23b

Thank you !.

**Comment by MintChocoO2C** [comment]
안녕하세요 답변감사드립니다.

./gossm 로 접속을 해서 방향키를 사용을 하여 리즌과 서버를 고르면 privaate subnet에 있는 서버 접속이 가능합니다. 
제가 알기로는 Client가 서버에 직접 붙는게 아닌 AWS를 통해 넘어가는 걸로 알고있습니다.

그래서 public subnet를 반드시 사용해야 할 필요가 없을 듯 합니다.

**Comment by gjbae1212** [comment]
Hello friend.

I have known wrong it. 

I can check to possibly access to private ec2 using SSM, processing additional steps.

This issue is to run it to terminal UI, but not run command line, right?

I will check this issue.  

Thank you!.

**Comment by gjbae1212** [comment]
Thank you. 
Upgrade gossm v1.1.1, try it.
