### ISSUE TITLE
인라인으로 접속 할때 에러가 발생합니다. #7

### ISSUE THREAD

**Issue by MintChocoO2C** [gjbae1212/gossm#8]
안녕하세요 답변감사드립니다.

./gossm 로 접속을 해서 방향키를 사용을 하여 리즌과 서버를 고르면 privaate subnet에 있는 서버 접속이 가능합니다. 
제가 알기로는 Client가 서버에 직접 붙는게 아닌 AWS를 통해 넘어가는 걸로 알고있습니다.

그래서 public subnet를 반드시 사용해야 할 필요가 없을 듯 합니다.

_Originally posted by @MintChocoO2C in https://github.com/gjbae1212/gossm/issues/7#issuecomment-724437120_

**Comment by gjbae1212** [comment]
Thank you.
Upgrade gossm v1.1.1, try it.
