### ISSUE TITLE
Cannot get the aws credentials from the environment variables

### ISSUE THREAD

**Issue by daeho-ro** [gjbae1212/gossm#9]
I usually use the STS assume role or MFA verification that gives the session token. After that, I put it to the environment variable and use the AWS CLI. However, this application cannot get the env. variables, just read the ~/.aws/credentials file only. Can you add this feature?

**Comment by Rendanic** [comment]
Hi
what do you exactly mean?
I always work with environment variables from AWS SSO. That's perfectly working.

**Comment by daeho-ro** [comment]
Oh, it is worked indeed. I did something wrong, sorry.
